{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "888948fc-12b0-4cb8-81b2-cd68aa33b5c8",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "from scipy.signal import cont2discrete, place_poles\n",
    "\n",
    "\n",
    "class MPCVelControl:\n",
    "\n",
    "    def new_controller(self, rocket, Ts, H):\n",
    "        self.Ts = Ts\n",
    "        self.H = H\n",
    "\n",
    "        # Linearize around hover\n",
    "        xs, us = rocket.trim()\n",
    "        sys = rocket.linearize_sys(xs, us)\n",
    "\n",
    "        # Extract z-velocity subsystem\n",
    "        # States: [vz]\n",
    "        # Input: Pav\n",
    "        iz = sys.state_names.index(\"vz\")\n",
    "        iu = sys.input_names.index(\"Pavg\")\n",
    "\n",
    "        A = sys.A[np.ix_([iz], [iz])]\n",
    "        B = sys.B[np.ix_([iz], [iu])]\n",
    "\n",
    "        # Disturbance enters additively in acceleration\n",
    "        Bd = np.array([[1.0]])\n",
    "\n",
    "        # Discretize\n",
    "        Ad, Bd_u, _, _, _ = cont2discrete((A, B, np.eye(1), 0), Ts)\n",
    "        Bd_d = Ts * Bd\n",
    "\n",
    "        self.ctrl_z = MPCZOffsetFree(\n",
    "            Ad, Bd_u, Bd_d,\n",
    "            Ts=Ts,\n",
    "            umin=40.0,\n",
    "            umax=80.0\n",
    "        )\n",
    "\n",
    "        return self\n",
    "\n",
    "    def get_u(self, x):\n",
    "        \"\"\"\n",
    "        Called by rocket.simulate_control\n",
    "        \"\"\"\n",
    "        vz = np.array([x[8]])   # vz index = 8\n",
    "        u_z = self.ctrl_z.get_u(vz)\n",
    "\n",
    "        # Full input vector (keep others at trim)\n",
    "        u = np.zeros(4)\n",
    "        u[2] = u_z   # Pavg\n",
    "\n",
    "        return u\n",
    "\n",
    "\n",
    "class MPCZOffsetFree:\n",
    "    \"\"\"\n",
    "    Offset-free z-velocity MPC using disturbance observer\n",
    "    \"\"\"\n",
    "\n",
    "    def __init__(self, Ad, Bd, Bd_d, Ts, umin, umax):\n",
    "        self.Ad = Ad\n",
    "        self.Bd = Bd\n",
    "        self.Bd_d = Bd_d\n",
    "        self.Ts = Ts\n",
    "\n",
    "        self.umin = umin\n",
    "        self.umax = umax\n",
    "\n",
    "        self.nx = 1\n",
    "        self.nu = 1\n",
    "\n",
    "        # Estimates\n",
    "        self.x_hat = np.zeros(1)\n",
    "        self.d_hat = np.zeros(1)\n",
    "        self.u_prev = np.zeros(1)\n",
    "\n",
    "        # Augmented observer system\n",
    "        Aa = np.block([\n",
    "            [Ad, Bd_d],\n",
    "            [np.zeros((1, 1)), np.eye(1)]\n",
    "        ])\n",
    "        Ba = np.vstack([Bd, np.zeros((1, 1))])\n",
    "        Ca = np.hstack([np.eye(1), np.zeros((1, 1))])\n",
    "\n",
    "        # Observer poles (fast, stable)\n",
    "        poles = [0.4, 0.5]\n",
    "        self.L = place_poles(Aa.T, Ca.T, poles).gain_matrix.T\n",
    "\n",
    "        self.Aa = Aa\n",
    "        self.Ba = Ba\n",
    "        self.Ca = Ca\n",
    "\n",
    "    def get_u(self, x_meas):\n",
    "        \"\"\"\n",
    "        x_meas is treated as a measurement (per project hint)\n",
    "        \"\"\"\n",
    "\n",
    "        # ---- Observer update ----\n",
    "        xa = np.hstack([self.x_hat, self.d_hat])\n",
    "\n",
    "        xa = (\n",
    "            self.Aa @ xa\n",
    "            + self.Ba @ self.u_prev\n",
    "            + self.L @ (x_meas - self.Ca @ xa)\n",
    "        )\n",
    "\n",
    "        self.x_hat = xa[0:1]\n",
    "        self.d_hat = xa[1:2]\n",
    "\n",
    "        # ---- Offset-free control law ----\n",
    "        # u = -(x + disturbance compensation)\n",
    "        K = 3.0\n",
    "        u = -K * self.x_hat - self.d_hat\n",
    "\n",
    "        # Saturation\n",
    "        u = np.clip(u, self.umin, self.umax)\n",
    "\n",
    "        self.u_prev = np.array([u])\n",
    "        return u\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
